### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by zenminimalist** [rc2dev/dotfiles#4]
I'm trying to convert a Kindle Clippings HTML file via the command `python3 kindle2md /Users/David/Downloads/Clippings.html` but get the following error:

```
/opt/homebrew/bin/python3: can't open file '/Users/David/kindle2md': [Errno 2] No such file or directory
```
I've installed the python dependencies via pip3 install --user beautifulsoup4. 

Am I missing something?

**Comment by rc2dev** [comment]
Hi,

Have you downloaded `kindle2md` to your current directory?

**Comment by zenminimalist** [comment]
Ups, I thought that gets installed via the pip3 install --user beautifulsoup4 command 🤦🏼‍♂️
